
log:
  level: "debug"

server:
  port: "8080"

datasource:
  connection: "host=localhost user=postgres password=postgres dbname=postgres port=5432 sslmode=disable"

faults-detector:
  cron: "@every 1h"
  max-threads: 12

ina-client:
  base-url: "https://alerta.ina.gob.ar/a6"
  token: ""
security.enabled: true

keycloak:
  client: "monitoreo-web"
  secret: ""
  url: ""
  realm: "monitoreo"