
log:
  level: "debug"

server:
  port: "8080"

datasource:
  connection: "host=localhost user=postgres password=postgres dbname=postgres port=5432 sslmode=disable"

faults-detector:
  cron: "@every 1h"
  max-forecast-waiting-time-in-hours: 6

ina-client:
  base-url: "https://alerta.ina.gob.ar/a6"
  token: ""