// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/configuracion": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuracion"
                ],
                "summary": "Endpoint para obtener las configuraciones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.AllConfigurations"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuracion"
                ],
                "summary": "Endpoint para modificar una configuracion",
                "parameters": [
                    {
                        "description": "Modify configuration",
                        "name": "configuration",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.Configuration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuracion"
                ],
                "summary": "Endpoint para crear una configuracion",
                "parameters": [
                    {
                        "description": "Add configuration",
                        "name": "configuration",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateConfiguration"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/configuracion/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuracion"
                ],
                "summary": "Endpoint para obtener una configuracion por id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id de la configuracion",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.Configuration"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuracion"
                ],
                "summary": "Endpoint para eliminar una configuracion por id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id de la configuracion",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/errores/indicadores": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Endpoint para obtener las indicadores de errores",
                "parameters": [
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha de comienzo del periodo - valor por defecto: 7 dias atras",
                        "name": "timeStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha del final del periodo - valor por defecto: hoy",
                        "name": "timeEnd",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "uint",
                        "description": "Id de la configuracion",
                        "name": "configurationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ErrorIndicator"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/errores/por-dia": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Errores"
                ],
                "summary": "Endpoint para obtener las errores detectados por dia",
                "parameters": [
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha de comienzo del periodo - valor por defecto: 7 dias atras",
                        "name": "timeStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha del final del periodo - valor por defecto: hoy",
                        "name": "timeEnd",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la configuracion",
                        "name": "configurationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ErrorsCountPerDayAndType"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/filtro/estaciones": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Filtros"
                ],
                "summary": "Endpoint para obtener las estaciones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.StationFilter"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/filtro/procedimientos": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Filtros"
                ],
                "summary": "Endpoint para obtener los procedimientos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ProcedureFilter"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/filtro/variables": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Filtros"
                ],
                "summary": "Endpoint para obtener las variables",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.VariableFilter"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "get the status of the server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Show the status of the server.",
                "responses": {
                    "200": {
                        "description": "Server is up and running",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inputs/metricas-generales": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inputs"
                ],
                "summary": "Endpoint para obtener las metricas generales de inputs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.InputsGeneralMetrics"
                        }
                    }
                }
            }
        },
        "/series": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Endpoint para obtener las series configuradas de una configuracion",
                "parameters": [
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha de comienzo del periodo - valor por defecto: 7 dias atras",
                        "name": "timeStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha del final del periodo - valor por defecto: mañana",
                        "name": "timeEnd",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtro por ID de la serie",
                        "name": "streamId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtro por ID de la estacion",
                        "name": "stationId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtro por ID de procedimiento",
                        "name": "procId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtro por ID de variable",
                        "name": "varId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Numero de pagina, por defecto 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Cantidad de series por pagina, por defecto 15",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la configuracion",
                        "name": "configurationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamCardsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/series/comportamiento": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Endpoint para obtener las metricas de comportamiento",
                "parameters": [
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha de comienzo del periodo - valor por defecto: 7 dias atras",
                        "name": "timeStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha del final del periodo - valor por defecto: mañana",
                        "name": "timeEnd",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la configuracion",
                        "name": "configurationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.BehaviourStreamsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/series/curadas/{serie_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Series"
                ],
                "summary": "Endpoint para obtener los valores de una serie curada por id",
                "parameters": [
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha de comienzo del periodo - valor por defecto: 7 dias atras",
                        "name": "timeStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha del final del periodo - valor por defecto: 5 dias despues",
                        "name": "timeEnd",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Id de la serie",
                        "name": "serie_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamsDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/series/estaciones": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Series"
                ],
                "summary": "Endpoint para obtener el resumen de las series agrupado por estacion",
                "parameters": [
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha de comienzo del periodo - valor por defecto: 7 dias atras",
                        "name": "timeStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha del final del periodo - valor por defecto: 5 dias despues",
                        "name": "timeEnd",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ID de la configuracion",
                        "name": "configurationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamsPerStationResponse"
                        }
                    }
                }
            }
        },
        "/series/observadas/{serie_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Series"
                ],
                "summary": "Endpoint para obtener los valores de una serie observada por id",
                "parameters": [
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha de comienzo del periodo - valor por defecto: 7 dias atras",
                        "name": "timeStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha del final del periodo - valor por defecto: mañana",
                        "name": "timeEnd",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Id de la serie",
                        "name": "serie_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamsDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/series/pronosticadas/{calibrado_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Series"
                ],
                "summary": "Endpoint para obtener los valores de una serie pronosticadas por id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Id del calibrado",
                        "name": "calibrado_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.CalibratedStreamsDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/series/redes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Series"
                ],
                "summary": "Endpoint para obtener el resumen de las series agrupado por red",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamsPerNetworkResponse"
                        }
                    }
                }
            }
        },
        "/series/{serie_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Series"
                ],
                "summary": "Endpoint para obtener los datos de una serie dado un id y su configuracion",
                "parameters": [
                    {
                        "type": "string",
                        "format": "string",
                        "description": "Id de la configuracion de la serie",
                        "name": "configuredStreamId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha de comienzo del periodo - valor por defecto: 7 dias atras",
                        "name": "timeStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "2006-01-02",
                        "description": "Fecha del final del periodo - valor por defecto: mañana",
                        "name": "timeEnd",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Id de la serie",
                        "name": "serie_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.AllConfigurations": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.BehaviourStreamsResponse": {
            "type": "object",
            "properties": {
                "countAlertLevel": {
                    "type": "integer"
                },
                "countEvacuationLevel": {
                    "type": "integer"
                },
                "countLowWaterLevel": {
                    "type": "integer"
                },
                "totalValuesCount": {
                    "type": "integer"
                }
            }
        },
        "dtos.CalibratedStreamsData": {
            "type": "object",
            "properties": {
                "qualifier": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "dtos.CalibratedStreamsDataResponse": {
            "type": "object",
            "properties": {
                "mainStreams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.CalibratedStreamsData"
                    }
                },
                "p05Streams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.CalibratedStreamsData"
                    }
                },
                "p25Streams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.CalibratedStreamsData"
                    }
                },
                "p75Streams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.CalibratedStreamsData"
                    }
                },
                "p95Streams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.CalibratedStreamsData"
                    }
                }
            }
        },
        "dtos.Configuration": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Node"
                    }
                }
            }
        },
        "dtos.ConfiguredStream": {
            "type": "object",
            "properties": {
                "calibrationId": {
                    "type": "integer"
                },
                "checkErrors": {
                    "type": "boolean"
                },
                "configuredStreamId": {
                    "type": "integer"
                },
                "lowerThreshold": {
                    "type": "integer"
                },
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Metric"
                    }
                },
                "redundanciesIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "streamId": {
                    "type": "integer"
                },
                "streamType": {
                    "type": "integer"
                },
                "updateFrequency": {
                    "type": "number"
                },
                "upperThreshold": {
                    "type": "integer"
                }
            }
        },
        "dtos.CreateConfiguration": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.Node"
                    }
                }
            }
        },
        "dtos.ErrorIndicator": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "errorType": {
                    "type": "string"
                }
            }
        },
        "dtos.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "dtos.ErrorsCountPerDayAndType": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "errorType": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dtos.InputsGeneralMetrics": {
            "type": "object",
            "properties": {
                "totalNetworks": {
                    "type": "integer"
                },
                "totalStations": {
                    "type": "integer"
                },
                "totalStreams": {
                    "type": "integer"
                }
            }
        },
        "dtos.MetricCard": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "dtos.Node": {
            "type": "object",
            "properties": {
                "configuredStreams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ConfiguredStream"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.Pageable": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "totalElements": {
                    "type": "integer"
                }
            }
        },
        "dtos.ProcedureFilter": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.StationFilter": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dtos.StreamCard": {
            "type": "object",
            "properties": {
                "checkErrors": {
                    "type": "boolean"
                },
                "configuredStreamId": {
                    "type": "integer"
                },
                "procedureId": {
                    "type": "integer"
                },
                "procedureName": {
                    "type": "string"
                },
                "stationId": {
                    "type": "integer"
                },
                "stationName": {
                    "type": "string"
                },
                "streamId": {
                    "type": "integer"
                },
                "totalErrors": {
                    "type": "integer"
                },
                "variableId": {
                    "type": "integer"
                },
                "variableName": {
                    "type": "string"
                }
            }
        },
        "dtos.StreamCardsResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.StreamCard"
                    }
                },
                "pageable": {
                    "$ref": "#/definitions/dtos.Pageable"
                }
            }
        },
        "dtos.StreamData": {
            "type": "object",
            "properties": {
                "alertLevel": {
                    "type": "number"
                },
                "evacuationLevel": {
                    "type": "number"
                },
                "lowWaterLevel": {
                    "type": "number"
                },
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.MetricCard"
                    }
                },
                "owner": {
                    "type": "string"
                },
                "procId": {
                    "type": "integer"
                },
                "procedure": {
                    "type": "string"
                },
                "station": {
                    "type": "string"
                },
                "streamType": {
                    "type": "integer"
                },
                "unit": {
                    "type": "string"
                },
                "unitId": {
                    "type": "integer"
                },
                "updateFrequency": {
                    "type": "number"
                },
                "varId": {
                    "type": "integer"
                },
                "varName": {
                    "type": "string"
                }
            }
        },
        "dtos.StreamsData": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "dtos.StreamsDataResponse": {
            "type": "object",
            "properties": {
                "streams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.StreamsData"
                    }
                }
            }
        },
        "dtos.StreamsPerNetwork": {
            "type": "object",
            "properties": {
                "networkId": {
                    "type": "string"
                },
                "networkName": {
                    "type": "string"
                },
                "streamsCount": {
                    "type": "integer"
                }
            }
        },
        "dtos.StreamsPerNetworkResponse": {
            "type": "object",
            "properties": {
                "networks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.StreamsPerNetwork"
                    }
                }
            }
        },
        "dtos.StreamsPerStation": {
            "type": "object",
            "properties": {
                "errorCount": {
                    "type": "integer"
                },
                "stationId": {
                    "type": "string"
                },
                "stationName": {
                    "type": "string"
                },
                "streamsCount": {
                    "type": "integer"
                }
            }
        },
        "dtos.StreamsPerStationResponse": {
            "type": "object",
            "properties": {
                "stations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.StreamsPerStation"
                    }
                }
            }
        },
        "dtos.VariableFilter": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entities.Metric": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8
            ],
            "x-enum-comments": {
                "Maximo": "Configurable",
                "Media": "Configurable",
                "Mediana": "Configurable",
                "Minimo": "Configurable",
                "Nulos": "Configurable"
            },
            "x-enum-varnames": [
                "Mediana",
                "Media",
                "Maximo",
                "Minimo",
                "Nulos",
                "Observaciones",
                "AguasAlerta",
                "AguasEvacuacion",
                "AguasBajas"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Inputs API",
	Description:      "This API manages the inputs of the forecast model",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
