// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "get the status of the server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Show the status of the server.",
                "responses": {
                    "200": {
                        "description": "Server is up and running",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/inputs/metricas-generales": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Endpoint para obtener las metricas generales de inputs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.InputsGeneralMetrics"
                        }
                    }
                }
            }
        },
        "/series/estaciones": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Endpoint para obtener el resumen de las series agrupado por estacion",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamsPerStationResponse"
                        }
                    }
                }
            }
        },
        "/series/redes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Endpoint para obtener el resumen de las series agrupado por red",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.StreamsPerNetworkResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.InputsGeneralMetrics": {
            "type": "object",
            "properties": {
                "totalNetworks": {
                    "type": "integer"
                },
                "totalStations": {
                    "type": "integer"
                },
                "totalStreams": {
                    "type": "integer"
                }
            }
        },
        "dtos.StreamsPerNetwork": {
            "type": "object",
            "properties": {
                "networkId": {
                    "type": "string"
                },
                "networkName": {
                    "type": "string"
                },
                "streamsCount": {
                    "type": "integer"
                }
            }
        },
        "dtos.StreamsPerNetworkResponse": {
            "type": "object",
            "properties": {
                "networks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.StreamsPerNetwork"
                    }
                }
            }
        },
        "dtos.StreamsPerStation": {
            "type": "object",
            "properties": {
                "stationId": {
                    "type": "string"
                },
                "stationName": {
                    "type": "string"
                },
                "streamsCount": {
                    "type": "integer"
                }
            }
        },
        "dtos.StreamsPerStationResponse": {
            "type": "object",
            "properties": {
                "stations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.StreamsPerStation"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Inputs API",
	Description:      "This API manages the inputs of the forecast model",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
